[package]
name = "arithmetic-parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "parsing"
path = "src/lib.rs"  # Path to the main library source file

[dependencies]
char_reader = "0.1.1"

[profile.dev]
sanitize = ["address"]